/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 34424977d51f6d29bdf9cec73ec65729)
declare namespace Cloudflare {
	interface Env {
		NONCE_STORE: KVNamespace;
		JWT_SECRET: string;
		AWS_ACCESS_KEY_ID: string;
		AWS_SECRET_ACCESS_KEY: string;
		AWS_REGION: string;
		DATABASE_URL: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "JWT_SECRET" | "AWS_ACCESS_KEY_ID" | "AWS_SECRET_ACCESS_KEY" | "AWS_REGION" | "DATABASE_URL">> {}
}
